retrieveUnpackaged/objects/Bank__c.object
<CustomObject>
    <fields>
        <fullName>IFSCCode__c</fullName>
        <label>IFSC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Integration_Id__c</fullName>
        <externalId>true</externalId>
        <label>Integration Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MICRCode__c</fullName>
        <label>MICR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bank</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyDeveloperOrg/src/classes/sendBankingData.cls
global with sharing class sendBankingData
{
    
global class BankAcc{
        webservice Id Id;
}
global class Response
{
    	webservice List<Bank__c> IFSC;
        webservice List<Bank__c> MICR;
        webservice List<Bank__c> Priority;
}
        //webservice list<SystemWrapper> Response;

 
webservice static Response queryBank(BankAcc acc,Response res){
    	
    	res.IFSC=[SELECT IFSCCode__c FROM Bank__c where Integration_Id__c=:acc.Id];
     	res.MICR=[SELECT MICRCode__c FROM Bank__c where Integration_Id__c=:acc.Id];
    	res.Priority=[SELECT Name FROM Bank__c where Integration_Id__c=:acc.Id];
    	//acc.IFSC=IFSC;
    	//acc.MICR=MICR;
		return res;
	}    
    
}