retrieveUnpackaged/objects/Skill__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Skill Object contains skill for a particular domain</description>
    <fields>
        <fullName>Domain__c</fullName>
        <label>Domain</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technology__c</fullName>
        <label>Technology</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Skill Set</label>
</CustomObject>

MyDeveloperOrg/src/classes/CustomSettingsListController.cls
public with sharing class CustomSettingsListController {

    List<Skill__c> skilllist = Skill__c.getAll().values();
  public List<Skill__c> selectskills {
      get{
          return skilllist;
      }
      set;
  }

  public List<selectOption> isoCodes {
    get {
      List<selectOption> options = new List<selectOption>();

      for (Skill__c ski : Skill__c.getAll().values())
        options.add(new SelectOption(ski.Technology__c,ski.Domain__c+' - '+ski.Technology__c));
      return options;

    }
    set;
  }

}