retrieveUnpackaged/objects/TestB__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>TestBs</relationshipLabel>
        <relationshipName>TestBs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Day_of_Month__c</fullName>
        <defaultValue>DAY( DATE(2015,4,01) )</defaultValue>
        <label>Day of Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shipping_Location__c</fullName>
        <label>Shipping Location</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>TestB</label>
    <nameField>
        <label>TestB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestBs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MyDeveloperOrg/src/classes/PrimaryFlagHandler.cls
public class PrimaryFlagHandler {

    public void oninsert(List<TestB__c> testb)
    {
        //Integer [] numofdays;
        Map<Id,String> numofdays = new Map<Id,String>();
        List<TestB__c> tb;
        Account acc;
        
       for(TestB__c t: testb)
        {
            	
         	   tb = [SELECT Account__c,Shipping_Location__c,Primary_Flag__c FROM TestB__c where Id =: t.Id];
				for(TestB__c t1:tb)  
                {
                    numofdays.put(t1.Account__c,t1.Shipping_Location__c);
                    acc = [SELECT ShippingCity FROM Account where Id=:t1.Account__c];
                    if(t1.Primary_Flag__c)
                    {
                         acc.ShippingCity = numofdays.get(t1.Account__c);
                    }
                     
                }
            
        }
        update acc;
        
        //Integer numofday = [SELECT Day_of_Month__c,Id FROM TestB__c where Id:= testb.]
    }
    public void onupdate(List<TestB__c> testb,List<TestB__c> testoldmapb)
    {
        
    }
}